### ISSUE TITLE
NullPointerException after changing device lock

### ISSUE THREAD

**Issue by neosimsim** [AzureAD/rms-sdk-ui-for-android#2]
If I use this lib on a device without any device lock (password or pin) it works fine. If I activate device lock after installing and using the app once I get a NullPointerException. If I delete the app's content and try again it works. After I disable device lock the same.
- Nexus 5, Android 5.1.0
- Nexus 9, Android 5.0.1

Logcat:

``` Java
    E/AndroidRuntime(26826): java.lang.RuntimeException: An error occured while executing doInBackground()
    E/AndroidRuntime(26826):    at android.os.AsyncTask$3.done(AsyncTask.java:300)
    E/AndroidRuntime(26826):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    E/AndroidRuntime(26826):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    E/AndroidRuntime(26826):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    E/AndroidRuntime(26826):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    E/AndroidRuntime(26826):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    E/AndroidRuntime(26826):    at java.lang.Thread.run(Thread.java:818)
    E/AndroidRuntime(26826): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.microsoft.rightsmanagement.utils.SemiSecureClock.getCurrentTimeInMillis()' on a null object reference
    E/AndroidRuntime(26826):    at com.microsoft.rightsmanagement.identity.IdentityStore.getServiceDiscoveryDetails(IdentityStore.java:76)
    E/AndroidRuntime(26826):    at com.microsoft.rightsmanagement.flows.PrivateFlowUtils.getServiceDiscoveryDetails(PrivateFlowUtils.java:57)
    E/AndroidRuntime(26826):    at com.microsoft.rightsmanagement.flows.GetTemplatesFlow.getTemplateArray(GetTemplatesFlow.java:104)
    E/AndroidRuntime(26826):    at com.microsoft.rightsmanagement.flows.GetTemplatesFlow.doInBackground(GetTemplatesFlow.java:73)
    E/AndroidRuntime(26826):    at com.microsoft.rightsmanagement.flows.GetTemplatesFlow.doInBackground(GetTemplatesFlow.java:28)
    E/AndroidRuntime(26826):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    E/AndroidRuntime(26826):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    E/AndroidRuntime(26826):    ... 3 more
```

I tried to dig this through and it seems be actually caused by a bad padding exception.

The crash seems to happen in OfflineKeyManagerV2.retreiveOfflineKeyInternal(Context)

``` Java
    this.mOfflineKey = (SecretKey)wrapCipher.unwrap(wrappedOfflineKeyBlob, "AES", 3);
```

I'm afraid that the AndroidKeyStore is messing something up.

**Comment by raeitan** [comment]
Hey Neosimsim, 
I have seen this issue before and from what I could tell it only happens while debugging the application, while writing to the key store in debug mode there is a chance that the storage will be corrupted, please uninstall your application manually, and re-install to clear the corrupt cache.  
I've opened a bug on this to track it on our system, the fix would be to clear all the offline data in this scenario. 
Thanks
